name: Cypress run test

on:
  push:
    branches: [main]
  pull-request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          name: run test
          run: npm run test
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: cypress/reports/html/*.html