name: Cypress Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTION_ROLE: ${{ secrets.ACTION_ROLE }}
  REGION: ${{ secrets.REGION }}
  BUCKET: ${{ secrets.BUCKET }}
  SNS_EMAIL: ${{ secrets.SNS_EMAIL }}

permissions:
  contents: read
  id-token: write

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Insall dependencies
        run: npm i
      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test
      - name: Upload Cypress repository
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/
  
  upload-to-s3:
    runs-on: ubuntu-latest
    needs: run-cypress
    steps:
      - name: Download Cypress report
        uses: actions/download-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/
      - name: Compress reports folder to zip
        run: |
          zip -r report.zip cypress/reports/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ACTION_ROLE }}
          aws-region: ${{ env.REGION }}
      - name: Upload reports to S3
        run: |
          aws s3 cp report.zip s3://${{ env.BUCKET }}/reports/report-${{ github.run_number }}.zip
      - name: Send test summary via Email
        run: |
          aws sns publish \
          --topic-arn ${{ env.SNS_EMAIL }} \
          --message "Cypress Test Completed!
          Report: s3://${{ env.BUCKET }}/reports/report-${{ github.run_number }}.zip
          Status: Pass" \
          --subject "Cypress Test Report - ${{ github.run_number }}" \
          --region ${{ env.REGION }}

 




