name: Cypress run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Insall dependencies
        run: npm i
      - uses: cypress-io/github-action@v6
        with:
          name: run test
          command: npm run test
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: cypress/reports/html/*.html