name: Upload reports to S3

on:
  workflow_run:
    workflows: ["Cypress run test"]
    types:
      - completed

env:
  REGION: ${{ secrets.REGION }}
  ACTION_ROLE: ${{ secrets.ACTION_ROLE }}
  BUCKET: ${{ secrets.BUCKET }}

permissions:
  contents: read
  id-token: write

jobs:
  Upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Cypress report
        uses: actions/download-artifcat@v4
        with:
          name: cypress-report
          path: cypress/reports/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ACTION_ROLE }}
          aws-region: ${{ env.REGION }}
      - name: Upload reports to S3
        run: |
          aws s3 cp cypress/reports s3://${{ env.BUCKET }}/reports/report-${{ github.run_number }}




